# 使用的主題
theme = "mini"

# 網站網址，先維持預設
baseURL = 'https://example.org/'

# 預設網站語言
languageCode = 'zh-TW'

# 網站標題
title = 'wyStuff'

# 部署時執行的指令
[build]
  publish = "public"
  command = "hugo --gc --minify"

# 指定Hugo版本，應與本機安裝的Hugo版本一致
[build.environment]
  HUGO_VERSION = "0.121.1"